// AUTO-GENERATED by Zeyon sync

import { HeaderView as HeaderView_YOP0DF59HT } from '../src/components/headerView';
import { AboutRoute as AboutRoute_24QVDJQR03 } from '../src/routes/aboutRoute';
import { HomeRoute as HomeRoute_2NKSOTYJGD } from '../src/routes/homeRoute';

export const classMapData = {
  'component-header': {
    classRef: HeaderView_YOP0DF59HT,
    type: 'View',
  },
  'route-about': {
    classRef: AboutRoute_24QVDJQR03,
    type: 'RouteView',
  },
  'route-home': {
    classRef: HomeRoute_2NKSOTYJGD,
    type: 'RouteView',
  },
};
