// AUTO-GENERATED by Zeyon sync

import { HeaderView as HeaderView_R900IZNK1C } from '../src/components/headerView';
import { AboutRoute as AboutRoute_0QXL504DK1 } from '../src/routes/aboutRoute';
import { HomeRoute as HomeRoute_0ONK3H1FBE } from '../src/routes/homeRoute';

export const classMapData = {
  'component-header': {
    classRef: HeaderView_R900IZNK1C,
    type: 'View',
  },
  'route-about': {
    classRef: AboutRoute_0QXL504DK1,
    type: 'RouteView',
  },
  'route-home': {
    classRef: HomeRoute_0ONK3H1FBE,
    type: 'RouteView',
  },
};
